name: Add publications from Zotero

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  open-pull-requests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - run: deno run --no-lock -A scripts/add-publications.ts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
