name: Add publications from Zotero

on:
  workflow_dispatch:

jobs:
  Style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - run: deno run -A scripts/main.ts

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        id: cpr
        with:
          token: ${{ secrets.PAT }}
          commit-message: Add zotero publications
          title: Add zotero publications
          body: Automated PR. Add publications from Zotero.
          branch: new-publications
          delete-branch: true
